"""
Django settings for innovarpa project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configuración de archivos estáticos
STATIC_DIR = '/static/images'
#STATICFILES_DIRS = [BASE_DIR / 'static',]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-so^r@o+i4v=@!^%*#5+cqka@av1zor3jp@r)gv5wl)0fx@@ogx'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#LOGIN_URL = '/login/'

#LOGIN_REDIRECT_URL = '/crud_usuarios/dashboard.html'

#LOGIN_REDIRECT_URL = '/indicador'
#LOGOUT_REDIRECT_URL = '/login'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'innovarpa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'innovarpa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',  # Motor de la base de datos
#        'NAME': 'innova',  # Nombre de la base de datos
#        'USER': 'root',                   # Usuario de la base de datos
#        'PASSWORD': '',            # Contraseña del usuario
#        'HOST': 'localhost',                     # O la dirección IP del servidor de la base de datos
#        'PORT': '3306',                          # Puerto de MySQL (por defecto es 3306)
#    }
#}





#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
##        'NAME': 'InventarioInnova',
#        'USER': 'sysadmin',
#        'PASSWORD': 'admin',
#        'HOST': '34.44.25.151',  # IP pública de tu instancia de Google Cloud SQL
#        'PORT': '3306',
#        'OPTIONS': {
#            'ssl': {
#                'ca': 'C:/innova/admin/certs/CA.pem',  # Ruta al certificado CA
#                'cert': 'C:/innova/admin/certs/client-cert.pem',  # Ruta al certificado del cliente
#                'key': 'C:/innova/admin/certs/client-key.pem',  # Ruta a la clave del cliente
#            }
#        },
#    }
#}





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'InventarioInnova',
        'USER': 'sysadmin',
        'PASSWORD': 'admin',
        'HOST': '34.44.25.151',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {
                'key': 'C:/innova/admin/innovarpa/panel/ssl_certs/client-key.pem',
                'cert': 'C:/innova/admin/innovarpa/panel/ssl_certs/client-cert.pem',
                'ca': 'C:/innova/admin/innovarpa/panel/ssl_certs/server-ca.pem',                
            },
        },
    }
}





#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'innova',
#        'USER': 'root',
#        'PASSWORD': '',
#       'HOST': 'localhost',
#        'PORT': '3306',
    
#    }
#}




#DATABASES = {
#   'default': {
#        'ENGINE': 'django.db.backends.oracle',
#        'NAME': 'xe',  # Nombre de tu base de datos
#        'USER': 'SYSTEM',          # Usuario de la base de datos
#        'PASSWORD': '2064.fariih',   # Contraseña del usuario
#        'HOST' : 'localhost',             # Puerto por defecto de Oracle
#        'PORT' : '1521'
#    }
#}






# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_FILES_DIRS = [STATIC_DIR,]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRISPY_TEMPLATE_PACK = 'bootstrap5'  # O usa 'bootstrap5' si prefieres la versión 5
#+DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.oracle',
#        'NAME': 'localhost:1521/xe',
#        'USER': 'SYSTEM',
#        'PASSWORD': '2064.fariih',
#        'TEST': {
#            'USER': '',
#            'TBLSPACE': '',
#            'TBLSPACE_TMP': '',
#        },
#    },

#}

# myproject/settings.py
LOGIN_URL = '/accounts/login/' 





EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Cambia esto si usas otro proveedor
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'farias.vidal.farias34@gmail.com'  # Tu dirección de correo
EMAIL_HOST_PASSWORD = 'bcyj ttvb ewpv tqso'
 #Tu contraseña de correo
 # Cambia 'mi_app' por el nombre de tu aplicación
#LOGGING = {
#    'version': 1,
#    'disable_existing_loggers': False,
#    'handlers': {
#        'console': {
#            'level': 'DEBUG',
#            'class': 'logging.StreamHandler',
#        },
#    },
#    'loggers': {
#        'django': {
#            'handlers': ['console'],
#            'level': 'DEBUG',
#            'propagate': True,
#        },
#    },
#}
